### ISSUE TITLE
machine resource used in the experiment

### ISSUE THREAD

**Issue by xwjim** [lanyunshi/Multi-hopComplexKBQA#12]
Hi. My lab is short of gpus. I want to know what is the machine resource used in the experiment and the time consuming.

**Comment by lanyunshi** [comment]
Hi,

Our GPU config is as follows:

![image](https://user-images.githubusercontent.com/7372818/93292280-c918bf80-f817-11ea-9148-461a2a74c46e.png)

If you don't have a large memory in your GPU, you can slightly tune the parameter args.train_limit_number to fit your machine. 

Regarding the training time, it costs several hours to train on WBQ and CQ datasets but it costs around 2 weeks on CWQ dataset the first time I trained on CWQ, because the code is querying the database all the time. After I collected a large KB cache, later on, it costs only 3-4 days to train on the CWQ dataset. Also the training time is different based on your database and machine configurations.

**Comment by xwjim** [comment]
> Hi,
> 
> Our GPU config is as follows:
> 
> ![image](https://user-images.githubusercontent.com/7372818/93292280-c918bf80-f817-11ea-9148-461a2a74c46e.png)
> 
> If you don't have a large memory in your GPU, you can slightly tune the parameter args.train_limit_number to fit your machine.
> 
> Regarding the training time, it costs several hours to train on WBQ and CQ datasets but it costs around 2 weeks on CWQ dataset the first time I trained on CWQ, because the code is querying the database all the time. After I collected a large KB cache, later on, it costs only 3-4 days to train on the CWQ dataset. Also the training time is different based on your database and machine configurations.

Thank you
